stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  VIEWER_USE_CRASHPAD: "TRUE"

.win_build: &win_build
  stage: build
  tags:
    - autobuild
    - windows
  before_script:
    - pipenv install
  script:
    - If ($env:VIEWER_CHANNEL_TYPE -eq 'Project') 
      { 
          $env:VIEWER_CHANNEL_CODENAME = $env:CI_COMMIT_REF_NAME[8..100] -join '' 
      }
    - pipenv run autobuild configure -c ReleaseOS -- -DUSE_FMODSTUDIO=ON -DUSE_NVAPI=ON -DUSE_LTO=ON -DVS_DISABLE_FATAL_WARNINGS=ON -DUSE_CRASHPAD=$env:VIEWER_USE_CRASHPAD
    - pipenv run autobuild build -c ReleaseOS --no-configure
    - If ($env:VIEWER_USE_CRASHPAD) {
    - Push-Location .\build-vc-*\newview\Release\
#    - If ($env:VIEWER_CHANNEL_TYPE -eq 'Project') { $env:SENTRY_PROJECT = $env:SENTRY_PROJECT_NONPROD } ElseIf ($env:VIEWER_CHANNEL_TYPE -eq 'Beta' -OR $env:VIEWER_CHANNEL_TYPE -eq 'Release') {$env:SENTRY_PROJECT = $env:SENTRY_PROJECT_NONPROD }
    - sentry-cli upload-dif alchemy-bin.exe alchemy-bin.pdb crashpad_handler.exe crashpad_handler.pdb openjpeg.pdb openjpeg.dll fmod.dll libcrypto-1_1-x64.dll libcrypto-1_1-x64.pdb libssl-1_1-x64.dll libssl-1_1-x64.pdb vcruntime140.dll msvcp140.dll nghttp2.dll glod.dll
    - Pop-Location }
  artifacts:
    name: "$env:CI_COMMIT_REF_NAME-$env:CI_COMMIT_SHORT_SHA"
    expire_in: 4 week
    paths:
      - build-vc-*/newview/Release/build_data.json
      - build-vc-*/newview/Release/alchemy-bin.pdb
      - build-vc-*/newview/Release/Alchemy_*_Setup.exe
      
build:master:windows32:
  <<: *win_build
  variables:
    AUTOBUILD_ADDRSIZE: 32
    VIEWER_CHANNEL_TYPE: Test
    VIEWER_USE_CRASHPAD: "FALSE"
  only:
    - schedules

build:master:windows64:
  <<: *win_build
  variables:
    AUTOBUILD_ADDRSIZE: 64
    VIEWER_CHANNEL_TYPE: Test
    VIEWER_USE_CRASHPAD: "FALSE"
  only:
    - schedules

build:project:windows32:
  <<: *win_build
  variables:
    AUTOBUILD_ADDRSIZE: 32
    VIEWER_CHANNEL_TYPE: Project
    VIEWER_CRASHPAD_URL: $SENTRY_DSN_NONPROD
    SENTRY_PROJECT: $SENTRY_PROJECT_NONPROD
  only:
    - /^project-.*$/
    - schedules
  except:
    - beta
    - release
      
build:project:windows64:
  <<: *win_build
  variables:
    AUTOBUILD_ADDRSIZE: 64
    VIEWER_CHANNEL_TYPE: Project
    VIEWER_CRASHPAD_URL: $SENTRY_DSN_NONPROD
    SENTRY_PROJECT: $SENTRY_PROJECT_NONPROD
  only:
    - /^project-.*$/
    - schedules
  except:
    - beta
    - release

build:beta:windows32:
  <<: *win_build
  variables:
    AUTOBUILD_ADDRSIZE: 32
    VIEWER_CHANNEL_TYPE: Beta
    VIEWER_CRASHPAD_URL: $SENTRY_DSN_PROD
    SENTRY_PROJECT: $SENTRY_PROJECT_PROD
  only:
    - beta
    - schedules
  except:
    - /^project-.*$/
    - release
      
build:beta:windows64:
  <<: *win_build
  variables:
    AUTOBUILD_ADDRSIZE: 64
    VIEWER_CHANNEL_TYPE: Beta
    VIEWER_CRASHPAD_URL: $SENTRY_DSN_PROD
    SENTRY_PROJECT: $SENTRY_PROJECT_PROD
  only:
    - beta
    - schedules
  except:
    - /^project-.*$/
    - release

build:release:windows32:
  <<: *win_build
  variables:
    AUTOBUILD_ADDRSIZE: 64
    VIEWER_CHANNEL_TYPE: Release
    VIEWER_CRASHPAD_URL: $SENTRY_DSN_PROD
    SENTRY_PROJECT: $SENTRY_PROJECT_PROD
  only:
    - release
    - schedules
  except:
    - /^project-.*$/
    - beta

build:release:windows64:
  <<: *win_build
  variables:
    AUTOBUILD_ADDRSIZE: 64
    VIEWER_CHANNEL_TYPE: Release
    VIEWER_CRASHPAD_URL: $SENTRY_DSN_PROD
    SENTRY_PROJECT: $SENTRY_PROJECT_PROD
  only:
    - release
    - schedules
  except:
    - /^project-.*$/
    - beta

deploy:nexus:
  stage: deploy
  tags:
    - autobuild
    - windows
  script:
    - $BuildData = Get-Content .\build-vc-64\newview\Release\build_data.json | ConvertFrom-Json
    - $UploadDestViewerDir = $BuildData."Channel".ToLower().Replace(" ", "/")
    - $UploadDestVer = $BuildData."Version"
    - $UploadDestURL = "https://pkg.alchemyviewer.org/repository/viewer/${$UploadDestViewerDir}/${$UploadDestVer}"

    - $UploadParams = @{
      UseBasicParsing = $true
      Method          = "PUT"
      Headers         = @{
        ContentType   = "application/x-executable"
        Authorization = "Basic $([System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes("$env:AUTOBUILD_HTTP_USER`:$env:AUTOBUILD_HTTP_PASS")))" 
        }
      Verbose         = $true
      }

    - Push-Location .\build-vc-32\newview\Release\
    - $FileNameWin32 = Get-ChildItem -Path . -Name -Include Alchemy_*_Setup.exe
    - Invoke-WebRequest @$UploadParams -InFile .\$FileNameWin32 --Uri "${$UploadDestURL}/${FileNameWin32}"
    - Pop-Location

    - Push-Location .\build-vc-64\newview\Release\
    - $FileNameWin64 = Get-ChildItem -Path . -Name -Include Alchemy_*_Setup.exe
    - Invoke-WebRequest @$UploadParams -InFile .\$FileNameWin32 --Uri "${$UploadDestURL}/${FileNameWin64}"
    - Pop-Location
  when: manual
  only:
    - /^project-.*$/
    - beta
    - release
  except:
    - master